#pragma once

#include <esp_heap_caps.h>

#include <csetjmp>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <new>
#include <utility>
#include <vector>

namespace lua_nodemcu_viper::internal
{

    // Maximum IR instructions generated by one C-like function, limiting oversized script-side compilations.
    static constexpr size_t kMaxInstructions = 4096;
    // Maximum variables/temporaries in one function, including parameters, locals, constants, and expression temporaries.
    static constexpr size_t kMaxVariables = 1024;
    // Maximum final machine-code size for one native function, limiting executable memory use.
    static constexpr size_t kMaxNativeCodeBytes = 65536;
    // Maximum number of 32-bit literals allowed in one native function's literal pool.
    static constexpr size_t kMaxNativeLiterals = 256;
    // Maximum number of native call arguments; argument types are cached in CompiledFunction so compile-time vars can be released.
    static constexpr size_t kMaxNativeParams = 128;
    // IR size limit for temporary register forwarding; currently covers whole functions to keep hot-path temporaries out of the local frame.
    static constexpr size_t kMaxTempForwardingInstructions = kMaxInstructions;
    // Threshold for preferring internal RAM for compile-time working sets; larger allocations prefer PSRAM to reduce internal RAM pressure.
    static constexpr size_t kViperWorkInternalLimitBytes = 16U * 1024U;
    // Threshold for preferring internal RAM for small viper.buf allocations; larger buffers prefer PSRAM.
    static constexpr size_t kViperBufferInternalLimitBytes = 4U * 1024U;

    void *alloc_viper_work_data(size_t bytes);

    struct ViperAllocScope
    {
        std::jmp_buf env;
        ViperAllocScope *previous = nullptr;
        const char *error = nullptr;
    };

    void enter_viper_alloc_scope(ViperAllocScope &scope);
    void leave_viper_alloc_scope(ViperAllocScope &scope);
    [[noreturn]] void fail_viper_alloc(const char *msg);

    struct ViperError
    {
        char text[160] = {};

        /**
         * @brief Clear the current error text.
         */
        void clear()
        {
            text[0] = '\0';
        }

        /**
         * @brief Return the error text, or the caller-provided default when empty.
         */
        const char *c_str(const char *fallback = "viper: error") const
        {
            return text[0] ? text : fallback;
        }

        /**
         * @brief Store a constant error text without dynamic string allocation.
         */
        void set(const char *msg)
        {
            std::snprintf(text, sizeof(text), "%s", msg ? msg : "viper: error");
            text[sizeof(text) - 1] = '\0';
        }

        /**
         * @brief Store a parse error with a source offset.
         */
        void set_near(const char *msg, size_t pos)
        {
            std::snprintf(text, sizeof(text), "%s near offset %llu",
                          msg ? msg : "viper.compile_c: parser error",
                          (unsigned long long)pos);
            text[sizeof(text) - 1] = '\0';
        }

        /**
         * @brief Store a native compilation error with an IR index.
         */
        void set_at_ir(const char *msg, size_t ir)
        {
            std::snprintf(text, sizeof(text), "%s at ir %llu",
                          msg ? msg : "viper native: compile error",
                          (unsigned long long)ir);
            text[sizeof(text) - 1] = '\0';
        }
    };

    template <typename T>
    struct ViperInternalAllocator
    {
        using value_type = T;

        template <typename U>
        struct rebind
        {
            using other = ViperInternalAllocator<U>;
        };

        ViperInternalAllocator() noexcept = default;

        template <typename U>
        ViperInternalAllocator(const ViperInternalAllocator<U> &) noexcept
        {
        }

        T *allocate(size_t n)
        {
            if (n == 0)
                return nullptr;
            if (n > std::numeric_limits<size_t>::max() / sizeof(T))
                fail_viper_alloc("viper.compile_c: allocation size overflow");

            void *ptr = alloc_viper_work_data(n * sizeof(T));
            if (!ptr)
                fail_viper_alloc("viper.compile_c: out of memory");
            return static_cast<T *>(ptr);
        }

        void deallocate(T *ptr, size_t) noexcept
        {
            if (ptr)
                heap_caps_free(ptr);
        }
    };

    template <typename T, typename U>
    bool operator==(const ViperInternalAllocator<T> &, const ViperInternalAllocator<U> &) noexcept
    {
        return true;
    }

    template <typename T, typename U>
    bool operator!=(const ViperInternalAllocator<T> &, const ViperInternalAllocator<U> &) noexcept
    {
        return false;
    }

    template <typename T>
    using ViperInternalVector = std::vector<T, ViperInternalAllocator<T>>;

    template <typename T>
    class ViperScopedObject
    {
    public:
        explicit ViperScopedObject(T *ptr = nullptr) : m_ptr(ptr) {}

        ~ViperScopedObject()
        {
            reset();
        }

        ViperScopedObject(const ViperScopedObject &) = delete;
        ViperScopedObject &operator=(const ViperScopedObject &) = delete;

        T *get() const
        {
            return m_ptr;
        }

        T *operator->() const
        {
            return m_ptr;
        }

        void reset()
        {
            if (!m_ptr)
                return;
            m_ptr->~T();
            heap_caps_free(m_ptr);
            m_ptr = nullptr;
        }

    private:
        T *m_ptr = nullptr;
    };

    template <typename T, typename... Args>
    static T *make_viper_work_object(Args &&...args)
    {
        void *mem = alloc_viper_work_data(sizeof(T));
        if (!mem)
            return nullptr;
        return new (mem) T(std::forward<Args>(args)...);
    }

    enum class ValueType : uint8_t
    {
        I32,
        U32,
        I16,
        U16,
        I8,
        U8,
        Bool,
        F32,
        Ptr8,
        Ptr16,
        Ptr32,
        PtrF32,
        Void,
    };

    enum class OpCode : uint8_t
    {
        Const,
        Mov,
        Add,
        AddI,
        AddI32,
        AddF,
        Sub,
        SubI,
        SubI32,
        SubF,
        Mul,
        MulI,
        MulI32,
        MulF,
        Div,
        DivI,
        DivF,
        Mod,
        Shl,
        Shr,
        BitAnd,
        BitOr,
        BitXor,
        Neg,
        NegI,
        NegF,
        Eq,
        EqI,
        EqF,
        Ne,
        NeI,
        NeF,
        Lt,
        LtI,
        LtF,
        Le,
        LeI,
        LeF,
        Gt,
        GtI,
        GtF,
        Ge,
        GeI,
        GeF,
        Load,
        Load8,
        Load8I32,
        Load16,
        Load16I32,
        Load32,
        Load32I32,
        LoadF32,
        Store,
        Store8,
        Store16,
        Store32,
        StoreF32,
        Jump,
        JumpIfFalse,
        Return,
    };

    struct Variable
    {
        ValueType type = ValueType::I32;
        bool is_param = false;
        bool is_const = false;
        bool is_temp = false;
        int64_t const_i = 0;
        float const_f = 0.0f;
    };

    struct Instruction
    {
        OpCode op = OpCode::Const;
        int a = 0;
        int b = 0;
        int c = 0;
        int64_t imm = 0;
        float fimm = 0.0f;
        ValueType type = ValueType::I32;
    };

    struct ViperNativeArg
    {
        uint32_t value = 0;
        uint32_t bytes = 0;
    };

    struct ViperNativeCall
    {
        const ViperNativeArg *args = nullptr;
        uint32_t *locals = nullptr;
    };

    using ViperNativeEntry = uint32_t (*)(const ViperNativeCall *call);

    struct ViperBuffer
    {
        uint8_t *data = nullptr;
        size_t bytes = 0;
    };

    struct CompiledFunction
    {
        ViperInternalVector<Variable> vars;
        ViperInternalVector<Instruction> code;
        uint8_t *native_code = nullptr;
        size_t native_size = 0;
        ViperNativeEntry native_entry = nullptr;
        uint32_t *native_frame = nullptr;
        size_t native_frame_words = 0;
        ViperInternalVector<uint32_t> native_local_words;
        ValueType param_types[kMaxNativeParams] = {};
        int param_count = 0;
        int return_reg = -1;
        ValueType return_type = ValueType::Void;
        bool unsafe_ptr = false;
        bool bounds_check = true;
    };

    /**
     * @brief Compare a source slice with constant text without constructing a temporary string.
     */
    inline bool viper_text_equals(const char *text, size_t len, const char *literal)
    {
        const size_t literal_len = literal ? std::strlen(literal) : 0;
        return text && literal && len == literal_len && std::memcmp(text, literal, len) == 0;
    }

    /**
     * @brief Convert a C scalar type-name source slice to a Viper value type.
     */
    inline bool parse_c_scalar_type_name(const char *name, size_t len, ValueType &out)
    {
        if (viper_text_equals(name, len, "int32_t"))
            out = ValueType::I32;
        else if (viper_text_equals(name, len, "uint32_t"))
            out = ValueType::U32;
        else if (viper_text_equals(name, len, "int16_t"))
            out = ValueType::I16;
        else if (viper_text_equals(name, len, "uint16_t"))
            out = ValueType::U16;
        else if (viper_text_equals(name, len, "int8_t"))
            out = ValueType::I8;
        else if (viper_text_equals(name, len, "uint8_t"))
            out = ValueType::U8;
        else if (viper_text_equals(name, len, "bool"))
            out = ValueType::Bool;
        else if (viper_text_equals(name, len, "float"))
            out = ValueType::F32;
        else if (viper_text_equals(name, len, "void"))
            out = ValueType::Void;
        else
            return false;
        return true;
    }

    inline bool pointer_type_for_scalar(ValueType scalar, ValueType &out)
    {
        if (scalar == ValueType::I8 || scalar == ValueType::U8 || scalar == ValueType::Bool ||
            scalar == ValueType::Void)
        {
            out = ValueType::Ptr8;
            return true;
        }
        if (scalar == ValueType::I16 || scalar == ValueType::U16)
        {
            out = ValueType::Ptr16;
            return true;
        }
        if (scalar == ValueType::I32 || scalar == ValueType::U32)
        {
            out = ValueType::Ptr32;
            return true;
        }
        if (scalar == ValueType::F32)
        {
            out = ValueType::PtrF32;
            return true;
        }
        return false;
    }

    inline bool is_ptr_type(ValueType type)
    {
        return type == ValueType::Ptr8 || type == ValueType::Ptr16 ||
               type == ValueType::Ptr32 || type == ValueType::PtrF32;
    }

    inline bool is_f32_type(ValueType type)
    {
        return type == ValueType::F32;
    }

    inline ValueType ptr_value_type(ValueType type)
    {
        return type == ValueType::PtrF32 ? ValueType::F32 : ValueType::I32;
    }

    inline size_t ptr_elem_size(ValueType type)
    {
        if (type == ValueType::Ptr16)
            return 2;
        if (type == ValueType::Ptr32 || type == ValueType::PtrF32)
            return 4;
        return 1;
    }

    inline OpCode load_opcode_for_ptr(ValueType type)
    {
        if (type == ValueType::Ptr16)
            return OpCode::Load16I32;
        if (type == ValueType::Ptr32)
            return OpCode::Load32I32;
        if (type == ValueType::PtrF32)
            return OpCode::LoadF32;
        return OpCode::Load8I32;
    }

    inline OpCode store_opcode_for_ptr(ValueType type)
    {
        if (type == ValueType::Ptr16)
            return OpCode::Store16;
        if (type == ValueType::Ptr32)
            return OpCode::Store32;
        if (type == ValueType::PtrF32)
            return OpCode::StoreF32;
        return OpCode::Store8;
    }

    inline OpCode typed_arith_opcode(OpCode op, ValueType result_type)
    {
        const bool use_f32 = result_type == ValueType::F32;
        if (op == OpCode::Add)
            return use_f32 ? OpCode::AddF : (result_type == ValueType::I32 ? OpCode::AddI32 : OpCode::AddI);
        if (op == OpCode::Sub)
            return use_f32 ? OpCode::SubF : (result_type == ValueType::I32 ? OpCode::SubI32 : OpCode::SubI);
        if (op == OpCode::Mul)
            return use_f32 ? OpCode::MulF : (result_type == ValueType::I32 ? OpCode::MulI32 : OpCode::MulI);
        if (op == OpCode::Div)
            return use_f32 ? OpCode::DivF : OpCode::DivI;
        return op;
    }

    inline OpCode typed_compare_opcode(OpCode op, bool use_f32)
    {
        if (op == OpCode::Eq)
            return use_f32 ? OpCode::EqF : OpCode::EqI;
        if (op == OpCode::Ne)
            return use_f32 ? OpCode::NeF : OpCode::NeI;
        if (op == OpCode::Lt)
            return use_f32 ? OpCode::LtF : OpCode::LtI;
        if (op == OpCode::Le)
            return use_f32 ? OpCode::LeF : OpCode::LeI;
        if (op == OpCode::Gt)
            return use_f32 ? OpCode::GtF : OpCode::GtI;
        if (op == OpCode::Ge)
            return use_f32 ? OpCode::GeF : OpCode::GeI;
        return op;
    }

    inline int64_t cast_scalar(int64_t value, ValueType type)
    {
        switch (type)
        {
        case ValueType::I8:
            return (int8_t)value;
        case ValueType::U8:
            return (uint8_t)value;
        case ValueType::I16:
            return (int16_t)value;
        case ValueType::U16:
            return (uint16_t)value;
        case ValueType::U32:
            return (uint32_t)value;
        case ValueType::Bool:
            return value ? 1 : 0;
        case ValueType::I32:
        default:
            return (int32_t)value;
        }
    }

    bool parse_viper_c(const char *src, bool unsafe_ptr, bool bounds_check,
                       CompiledFunction &fn, ViperError &err);
    bool compile_native(CompiledFunction &fn, ViperError &err);
    void release_native_storage(CompiledFunction &fn);

} // namespace lua_nodemcu_viper::internal
